# Generated by Django 4.2.4 on 2023-10-23 15:59

from django.db import migrations, models
import django.db.models.deletion
import users.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=20, unique=True)),
                ('has_paid', models.BooleanField(default=False)),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_agent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_picture', models.ImageField(blank=True, null=True, upload_to=users.utils.Util.custom_image_filename)),
                ('cnic_front', models.ImageField(blank=True, null=True, upload_to=users.utils.Util.custom_image_filename)),
                ('cnic_back', models.ImageField(blank=True, null=True, upload_to=users.utils.Util.custom_image_filename)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_Users', to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
